/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    AdsContent: typeof import('./src/components/AdsContent.vue')['default']
    AutoTalk: typeof import('./src/components/AutoTalk.vue')['default']
    Deals: typeof import('./src/components/Deals.vue')['default']
    Entertainment: typeof import('./src/components/Entertainment.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Life: typeof import('./src/components/Life.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeaGame: typeof import('./src/components/SeaGame.vue')['default']
    SmartAxiata: typeof import('./src/components/SmartAxiata.vue')['default']
    Sports: typeof import('./src/components/Sports.vue')['default']
    Starting: typeof import('./src/components/Starting.vue')['default']
    Technology: typeof import('./src/components/Technology.vue')['default']
    VanSticky: typeof import('vant/es')['Sticky']
  }
}
